# Generated by Django 4.2.6 on 2024-01-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcard',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
