# Generated by Django 4.2.6 on 2024-02-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_helpcard_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_card',
            name='created_till',
            field=models.DateField(),
        ),
    ]
