# Generated by Django 4.2.6 on 2024-02-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_todo_card_created_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_card',
            name='is_helping',
            field=models.BooleanField(default=False),
        ),
    ]
