# Generated by Django 4.2.6 on 2024-02-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_todo_card_is_helping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpcard',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='todo_card',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
